// Injects Open Graph / Twitter card tags into every dist/<name>/index.html and
// into dist/index.html, pointing at the thumbnails .github/preview.mjs took.
//
//   node .github/og.mjs
//
// Runs *after* preview.mjs (the images must exist) and after ./build-website.sh
// (dist/index.html must exist). Each head gets a marked block:
//
//   <!-- og:start --> … <!-- og:end -->
//
// which a second run replaces rather than appends, so it's idempotent. Titles
// and descriptions are read from the page itself — nothing to keep in sync.
//
// Env:
//   OG_SITE   absolute site URL, no trailing slash
//             (default https://abernier.github.io/examples)

import { readdir, readFile, writeFile, access } from "node:fs/promises";
import path from "node:path";

const SITE = (process.env.OG_SITE || "https://abernier.github.io/examples").replace(/\/+$/, "");
const SITE_NAME = "abernier/examples";
const SHOT = { width: 1280, height: 800 }; // preview.mjs VIEWPORT
const HOME_SHOT = { width: 1200, height: 630 }; // preview.mjs OG_VIEWPORT

const exists = (p) => access(p).then(() => true, () => false);

const decode = (s) =>
  s
    .replace(/&quot;/g, '"')
    .replace(/&#0?39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();

const attr = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const title = (html) => {
  const m = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  return m ? decode(m[1]) : null;
};

// <meta> attributes are often split across lines here, so read whole tags.
const meta = (html, name) => {
  for (const tag of html.match(/<meta\b[^>]*>/gi) ?? []) {
    const key = tag.match(/\bname\s*=\s*["']([^"']+)["']/i);
    if (key?.[1].toLowerCase() !== name) continue;
    const content = tag.match(/\bcontent\s*=\s*["']([\s\S]*?)["']/i);
    if (content) return decode(content[1]);
  }
  return null;
};

const BLOCK = /[ \t]*<!-- og:start[\s\S]*?<!-- og:end -->\n?/;

function render(tags) {
  const lines = tags
    .filter(([, value]) => value)
    .map(([property, value]) => {
      const key = property.startsWith("twitter:") ? "name" : "property";
      return `    <meta ${key}="${property}" content="${attr(String(value))}" />`;
    });
  return `    <!-- og:start (generated by .github/og.mjs) -->\n${lines.join("\n")}\n    <!-- og:end -->\n`;
}

async function inject(file, { url, image, imageSize }) {
  let html = await readFile(file, "utf8");

  // Hand-written cards win — only ever touch our own block.
  if (/property\s*=\s*["']og:image["']/i.test(html.replace(BLOCK, ""))) {
    console.log(`· ${file} (has its own og:image)`);
    return false;
  }
  if (!/<\/head>/i.test(html)) {
    console.log(`✗ ${file} — no </head>`);
    return false;
  }

  const block = render([
    ["og:type", "website"],
    ["og:site_name", SITE_NAME],
    ["og:title", title(html) ?? path.basename(path.dirname(file))],
    ["og:description", meta(html, "description")],
    ["og:url", url],
    ["og:image", image],
    ["og:image:width", image && imageSize.width],
    ["og:image:height", image && imageSize.height],
    ["twitter:card", image ? "summary_large_image" : "summary"],
  ]);

  html = BLOCK.test(html)
    ? html.replace(BLOCK, block)
    : html.replace(/([ \t]*)<\/head>/i, `${block}$1</head>`);

  await writeFile(file, html);
  return true;
}

const names = (await readdir("dist", { withFileTypes: true }))
  .filter((e) => e.isDirectory() && !e.name.startsWith("_"))
  .map((e) => e.name)
  .sort();

let written = 0;

for (const name of names) {
  const file = `dist/${name}/index.html`;
  if (!(await exists(file))) {
    console.log(`· ${name} (no index.html)`);
    continue;
  }
  const shot = `dist/_previews/${name}.jpg`;
  const done = await inject(file, {
    url: `${SITE}/${name}/`,
    image: (await exists(shot)) ? `${SITE}/_previews/${name}.jpg` : null,
    imageSize: SHOT,
  });
  if (done) {
    written++;
    console.log(`✓ ${name}`);
  }
}

// The gallery itself, built by ./build-website.sh — its image is the contact sheet.
if (await exists("dist/index.html")) {
  const mosaic = "dist/_previews/_home.jpg";
  const done = await inject("dist/index.html", {
    url: `${SITE}/`,
    image: (await exists(mosaic)) ? `${SITE}/_previews/_home.jpg` : null,
    imageSize: HOME_SHOT,
  });
  if (done) {
    written++;
    console.log("✓ index.html");
  }
} else {
  console.log("· index.html missing — run ./build-website.sh first");
}

console.log(`${written} page(s) tagged`);
